import { Service, Config } from "@cmmv/core";

@Service()
export class ChatGPTService {
    async generateContent(prompt: string) : Promise<string> {
        const openaiApiKey = Config.get("blog.openaiApiKey");

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 160000); // 160 seconds timeout

        try {
            const response = await fetch('https://api.openai.com/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${openaiApiKey || ''}`
                },
                body: JSON.stringify({
                    model: "gpt-4.1-mini",
                    messages: [
                        {
                            role: "user",
                            content: prompt
                        }
                    ],
                    temperature: 0.1,
                    max_tokens: 8000
                }),
                signal: controller.signal
            });

            if (!response.ok) {
                const error = await response.text();
                clearTimeout(timeoutId);
                throw new Error(`Failed to generate AI content: ${response.statusText}`);
            }

            const openaiResponse = await response.json();
            const generatedText = openaiResponse.choices?.[0]?.message?.content;

            if (!generatedText) {
                clearTimeout(timeoutId);
                throw new Error('No content generated by ChatGPT');
            }

            clearTimeout(timeoutId);
            return generatedText;
        } catch (error: unknown) {
            clearTimeout(timeoutId);
            
            if (error instanceof Error) {
                // Check for various abort/timeout error types
                if (error.name === 'AbortError' || 
                    error.message?.includes('aborted') || 
                    error.message?.includes('terminated') ||
                    error.message?.includes('signal') ||
                    error.message?.includes('The operation was aborted')) {
                    throw new Error('Request timeout: The AI service took longer than 160 seconds to respond');
                }
            }
            
            throw error;
        }
    }
}
